# Generated by Django 5.2.5 on 2025-08-21 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Emptable',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20)),
                ('baseSalary', models.IntegerField()),
                ('departmentId', models.IntegerField()),
            ],
        ),
    ]
